#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""


@author: tyler
"""

import folium
import pandas as pd

country_geo = './world-countries.json'
data = pd.read_csv('./Indicators.csv')

hist_indicator = 'CO2 emissions \(metric'
hist_year = 2011
mask1 = data['IndicatorName'].str.contains(hist_indicator)
mask2 = data['Year'].isin([hist_year])
stage = data[mask1 & mask2]
plot_data = stage[['CountryCode','Value']]

hist_indicator = stage.iloc[0]['IndicatorName']



#Using Folium
map = folium.Map(location=[100,0], zoom_start=1.5)
map.choropleth(geo_data = country_geo, data = plot_data, columns=['CountryCode','Value'],
               key_on='feautre.id',
               fill_color='YlGnBu', fill_opacity=0.7, line_opacity=0.2,
               legend_name=hist_indicator)
map.save('plot_data.html')


from IPython.display import HTML
HTML('<iframe src=plot_data.html width=700 height=450></iframe>')
